name: build and test

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            TARGET: linux

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: TF setup
        uses: hashicorp/setup-terraform@v2

      - name: test both stages
        working-directory: ./tests/both_stages
        shell: bash
        run: |
          terraform init
          terraform apply -auto-approve

      - name: test create parameters
        working-directory: ./tests/create_parameters
        shell: bash
        run: |
          terraform init
          terraform apply -auto-approve

      - name: test create stage
        working-directory: ./tests/create_stage
        shell: bash
        run: |
          terraform init
          terraform apply -auto-approve
